// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdwnD3mzdfVxsEtLl1nNP_5R3CNCHBtuw',
    appId: '1:435524159526:android:24655c9e638a5e7674bee7',
    messagingSenderId: '435524159526',
    projectId: 'heracle-78c85',
    storageBucket: 'heracle-78c85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3PyWdb4OsrOqupypXwL3ngFl2BE2KY04',
    appId: '1:435524159526:ios:21a2ef6d33eeecf374bee7',
    messagingSenderId: '435524159526',
    projectId: 'heracle-78c85',
    storageBucket: 'heracle-78c85.firebasestorage.app',
    androidClientId: '435524159526-c0mkhnappst0h64ovagb77aue6fp9f4g.apps.googleusercontent.com',
    iosClientId: '435524159526-obm23b0o4a5aek2p4vprud6b7e17idbo.apps.googleusercontent.com',
    iosBundleId: 'com.heracle.fit',
  );

}